---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.78, CPAN::Meta::Converter version 2.132661'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-ReadPassword-Win32
no_index:
  directory:
    - t
    - inc
requires:
  Term::ReadPassword: 0
  Test::More: 0
resources:
  repository: https://github.com/szabgab/Term-ReadPassword-Win32
version: 0.04
